name = "bill-beacon-notifications"
main = "src/index.js"
compatibility_date = "2026-09-06"
compatibility_flags = ["nodejs_compat", "enable_nodejs_http_modules"]
keep_vars = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "NOTIFICATIONS_KV"
id = "840fbd5bbad24c4caedeea2e2233fd82"

[triggers]
crons = ["*/5 * * * *"]