name = "bill-beacon-notifications"
main = "src/index.js"
compatibility_date = "2025-02-04"

[observability]
enabled = true

[[kv_namespaces]]
binding = "NOTIFICATIONS_KV"
id = "840fbd5bbad24c4caedeea2e2233fd82"

[triggers]
crons = ["*/5 * * * *"]